/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.itlachess.main.view;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Christian
 */
public class Board extends javax.swing.JFrame {
    private static Board instance;
    
    public static synchronized Board getInstance(){
        return instance == null ? instance = new Board() : instance;
    }
    /**
     * Creates new form Board
     */
    private Board() {
        /*Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("com.itlachess.main.view.img/icon.png"));
        setIconImage(icon);
        setVisible(true);*/
        initComponents();
        setLocationRelativeTo(null);
    }
    
  /*  @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("com.itlachess.main.view.img/icon.png"));


        return retValue;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btn7A = new javax.swing.JButton();
        btn7B = new javax.swing.JButton();
        btn7C = new javax.swing.JButton();
        btn7D = new javax.swing.JButton();
        btn7E = new javax.swing.JButton();
        btn7F = new javax.swing.JButton();
        btn7G = new javax.swing.JButton();
        btn7H = new javax.swing.JButton();
        btn6A = new javax.swing.JButton();
        btn6B = new javax.swing.JButton();
        btn6C = new javax.swing.JButton();
        btn6D = new javax.swing.JButton();
        btn6E = new javax.swing.JButton();
        btn6F = new javax.swing.JButton();
        btn6G = new javax.swing.JButton();
        btn6H = new javax.swing.JButton();
        btn5A = new javax.swing.JButton();
        btn5B = new javax.swing.JButton();
        btn5C = new javax.swing.JButton();
        btn5D = new javax.swing.JButton();
        btn5E = new javax.swing.JButton();
        btn5F = new javax.swing.JButton();
        btn5G = new javax.swing.JButton();
        btn5H = new javax.swing.JButton();
        btn4A = new javax.swing.JButton();
        btn4B = new javax.swing.JButton();
        btn4C = new javax.swing.JButton();
        btn4D = new javax.swing.JButton();
        btn4E = new javax.swing.JButton();
        btn4F = new javax.swing.JButton();
        btn4G = new javax.swing.JButton();
        btn4H = new javax.swing.JButton();
        btn3A = new javax.swing.JButton();
        btn3B = new javax.swing.JButton();
        btn3C = new javax.swing.JButton();
        btn3D = new javax.swing.JButton();
        btn3E = new javax.swing.JButton();
        btn3F = new javax.swing.JButton();
        btn3G = new javax.swing.JButton();
        btn3H = new javax.swing.JButton();
        btn2A = new javax.swing.JButton();
        btn2B = new javax.swing.JButton();
        btn2C = new javax.swing.JButton();
        btn2D = new javax.swing.JButton();
        btn2E = new javax.swing.JButton();
        btn2F = new javax.swing.JButton();
        btn2G = new javax.swing.JButton();
        btn2H = new javax.swing.JButton();
        btn1A = new javax.swing.JButton();
        btn1B = new javax.swing.JButton();
        btn1C = new javax.swing.JButton();
        btn1D = new javax.swing.JButton();
        btn1E = new javax.swing.JButton();
        btn1F = new javax.swing.JButton();
        btn1G = new javax.swing.JButton();
        btn1H = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ITLA Chess");
        setFocusableWindowState(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/itlachess/main/view/img/icon.png")).getImage());
        setLocationByPlatform(true);
        setName("Board"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jPanel1.add(jButton2);
        jPanel1.add(jButton3);
        jPanel1.add(jButton4);
        jPanel1.add(jButton5);
        jPanel1.add(jButton6);
        jPanel1.add(jButton9);
        jPanel1.add(jButton7);
        jPanel1.add(btn7A);
        jPanel1.add(btn7B);
        jPanel1.add(btn7C);
        jPanel1.add(btn7D);
        jPanel1.add(btn7E);
        jPanel1.add(btn7F);
        jPanel1.add(btn7G);

        btn7H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7HActionPerformed(evt);
            }
        });
        jPanel1.add(btn7H);
        jPanel1.add(btn6A);
        jPanel1.add(btn6B);
        jPanel1.add(btn6C);
        jPanel1.add(btn6D);
        jPanel1.add(btn6E);
        jPanel1.add(btn6F);
        jPanel1.add(btn6G);
        jPanel1.add(btn6H);
        jPanel1.add(btn5A);

        btn5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5BActionPerformed(evt);
            }
        });
        jPanel1.add(btn5B);
        jPanel1.add(btn5C);
        jPanel1.add(btn5D);
        jPanel1.add(btn5E);
        jPanel1.add(btn5F);
        jPanel1.add(btn5G);
        jPanel1.add(btn5H);
        jPanel1.add(btn4A);
        jPanel1.add(btn4B);
        jPanel1.add(btn4C);

        btn4D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4DActionPerformed(evt);
            }
        });
        jPanel1.add(btn4D);
        jPanel1.add(btn4E);
        jPanel1.add(btn4F);
        jPanel1.add(btn4G);
        jPanel1.add(btn4H);
        jPanel1.add(btn3A);
        jPanel1.add(btn3B);
        jPanel1.add(btn3C);
        jPanel1.add(btn3D);
        jPanel1.add(btn3E);
        jPanel1.add(btn3F);

        btn3G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3GActionPerformed(evt);
            }
        });
        jPanel1.add(btn3G);
        jPanel1.add(btn3H);
        jPanel1.add(btn2A);
        jPanel1.add(btn2B);
        jPanel1.add(btn2C);
        jPanel1.add(btn2D);
        jPanel1.add(btn2E);
        jPanel1.add(btn2F);
        jPanel1.add(btn2G);
        jPanel1.add(btn2H);
        jPanel1.add(btn1A);
        jPanel1.add(btn1B);
        jPanel1.add(btn1C);
        jPanel1.add(btn1D);
        jPanel1.add(btn1E);
        jPanel1.add(btn1F);
        jPanel1.add(btn1G);

        btn1H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1HActionPerformed(evt);
            }
        });
        jPanel1.add(btn1H);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 550, 540));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/itlachess/main/view/img/board.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn7HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7HActionPerformed

    private void btn5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5BActionPerformed

    private void btn4DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4DActionPerformed

    private void btn3GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3GActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3GActionPerformed

    private void btn1HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1HActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                
    }//GEN-LAST:event_formWindowClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1A;
    private javax.swing.JButton btn1B;
    private javax.swing.JButton btn1C;
    private javax.swing.JButton btn1D;
    private javax.swing.JButton btn1E;
    private javax.swing.JButton btn1F;
    private javax.swing.JButton btn1G;
    private javax.swing.JButton btn1H;
    private javax.swing.JButton btn2A;
    private javax.swing.JButton btn2B;
    private javax.swing.JButton btn2C;
    private javax.swing.JButton btn2D;
    private javax.swing.JButton btn2E;
    private javax.swing.JButton btn2F;
    private javax.swing.JButton btn2G;
    private javax.swing.JButton btn2H;
    private javax.swing.JButton btn3A;
    private javax.swing.JButton btn3B;
    private javax.swing.JButton btn3C;
    private javax.swing.JButton btn3D;
    private javax.swing.JButton btn3E;
    private javax.swing.JButton btn3F;
    private javax.swing.JButton btn3G;
    private javax.swing.JButton btn3H;
    private javax.swing.JButton btn4A;
    private javax.swing.JButton btn4B;
    private javax.swing.JButton btn4C;
    private javax.swing.JButton btn4D;
    private javax.swing.JButton btn4E;
    private javax.swing.JButton btn4F;
    private javax.swing.JButton btn4G;
    private javax.swing.JButton btn4H;
    private javax.swing.JButton btn5A;
    private javax.swing.JButton btn5B;
    private javax.swing.JButton btn5C;
    private javax.swing.JButton btn5D;
    private javax.swing.JButton btn5E;
    private javax.swing.JButton btn5F;
    private javax.swing.JButton btn5G;
    private javax.swing.JButton btn5H;
    private javax.swing.JButton btn6A;
    private javax.swing.JButton btn6B;
    private javax.swing.JButton btn6C;
    private javax.swing.JButton btn6D;
    private javax.swing.JButton btn6E;
    private javax.swing.JButton btn6F;
    private javax.swing.JButton btn6G;
    private javax.swing.JButton btn6H;
    private javax.swing.JButton btn7A;
    private javax.swing.JButton btn7B;
    private javax.swing.JButton btn7C;
    private javax.swing.JButton btn7D;
    private javax.swing.JButton btn7E;
    private javax.swing.JButton btn7F;
    private javax.swing.JButton btn7G;
    private javax.swing.JButton btn7H;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
