/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.itlachess.main.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;


/**
 *
 * @author Christian
 */
public class SignIn extends javax.swing.JFrame {
    
    private static SignIn instance;
    
    public static synchronized  SignIn getInstance(){
        return instance == null ? instance = new SignIn() : instance;
    }
    /**
     * Creates new form SignIn
     */
    private SignIn() {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("com.itlachess.main.view.img/icon.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExit = new javax.swing.JButton();
        BtnSignIn = new javax.swing.JButton();
        TxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/itlachess/main/view/img/icon.png")).getImage());
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 110, 40));

        BtnSignIn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnSignIn.setText("Sign in");
        BtnSignIn.setEnabled(false);
        BtnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, 40));

        TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldActionPerformed(evt);
            }
        });
        TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtFieldKeyPressed(evt);
            }
        });
        getContentPane().add(TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 150, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nickname:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        JBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/itlachess/main/view/img/SignIn.png"))); // NOI18N
        getContentPane().add(JBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignInActionPerformed
       this.dispose();
       ListUserAvailable.getInstance().setVisible(true);
    }//GEN-LAST:event_BtnSignInActionPerformed

    private void TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldActionPerformed

    }//GEN-LAST:event_TxtFieldActionPerformed

    private void TxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFieldKeyPressed
       if(!TxtField.getText().isEmpty()){
           BtnSignIn.setEnabled(true);
       }else{
           BtnSignIn.setEnabled(false);
       }
    }//GEN-LAST:event_TxtFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnSignIn;
    private javax.swing.JLabel JBackground;
    private javax.swing.JTextField TxtField;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
